### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by Pikurnose** [ballmc/weavemanagermacos#1]
when i launch lunar, and then relaunch with weave, it doesnt work.
It used to work, but suddenly stopped working one day for some reason. It said something to do with genesis files or something.
Help would be greatly appreciated
<img width="502" alt="Screen Shot 2024-02-12 at 8 30 22 PM" src="https://github.com/ballmc/weavemanagermacos/assets/159758070/bc06d4e3-83a0-4453-bc61-6a49e6566e2b">
<img width="511" alt="Screen Shot 2024-02-12 at 8 30 29 PM" src="https://github.com/ballmc/weavemanagermacos/assets/159758070/a8882d45-39cb-44f8-9219-653709558dda">
<img width="511" alt="Screen Shot 2024-02-12 at 8 30 29 PM" src="https://github.com/ballmc/weavemanagermacos/assets/159758070/c9138ad7-d671-45e8-a210-c2df9afb2e7a">
<img width="516" alt="Screen Shot 2024-02-12 at 8 30 35 PM" src="https://github.com/ballmc/weavemanagermacos/assets/159758070/4f5245cd-1571-413f-9644-cfeb08f2b37e">
<img width="506" alt="Screen Shot 2024-02-12 at 8 30 42 PM" src="https://github.com/ballmc/weavemanagermacos/assets/159758070/ffbe4517-a1cc-4ecb-a2ce-99bbde0561fe">
<img width="503" alt="Screen Shot 2024-02-12 at 8 30 49 PM" src="https://gith
[Uploading 2024-02-12-202928.log…]()
ub.com/ballmc/weavemanagermacos/assets/159758070/34dbdb4a-3ded-4d42-9e9a-07f68b9c7b5e">

**Comment by Pikurnose** [comment]
what do i do please help

**Comment by Pikurnose** [comment]
[2024-02-12-202928.log](https://github.com/ballmc/weavemanagermacos/files/14235925/2024-02-12-202928.log)

**Comment by ballmc** [comment]
Weave is broken right now due to a lunar update released yesterday. Wait for weave devs to update the weave loader agent jar or join the weave discord to stay notified.

**Comment by Pikurnose** [comment]
oh ok thanks so much. Can you please send me an invite link to weave discord? how long do you reckon it'll take to fix?

**Comment by ballmc** [comment]
I don't know how difficult the problem is to fix, but I would probably estimate a fix would come in the next few days to a week. 

https://discord.gg/eT4fuszu

**Comment by Pikurnose** [comment]
ok thanks so much

**Comment by Pikurnose** [comment]
even though thats a different weave to your one for mac, one that one is fixed will this one also be fixed?

**Comment by Pikurnose** [comment]
ohh ok got it. thanks

**Comment by Pikurnose** [comment]
will the new one be posted in announcements or something?

**Comment by ballmc** [comment]
Should be once its up

**Comment by Pikurnose** [comment]
bet
